version: '3.8'

services:
  cart-service:
    build:
      context: ./services/CartService
      dockerfile: Dockerfile
    ports:
      - "8083:8083"

  inventory-service:
    build:
      context: ./services/inventoryService
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  order-service:
    build:
      context: ./services/OrderService
      dockerfile: Dockerfile
    ports:
      - "8084:8084"

  payment-service:
    build:
      context: ./services/PaymentService
      dockerfile: Dockerfile
    ports:
      - "8085:8085"

  product-service:
    build:
      context: ./services/ProductService
      dockerfile: Dockerfile
    ports:
      - "8081:8081"

  eureka-server:
    build:
      context: ./infrastructure/EurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

