
# Application Name
spring.application.name=APIGateway

# Server Port
server.port=8080

# Eureka Server Connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Register with Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Enable service discovery routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true